name: Build and Deploy to Cloud Run (Artifact Registry)

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*", "release-*" ]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

concurrency:
  group: build-deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  # Repository variables (Settings → Secrets and variables → Actions → Variables)
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION || 'europe-west4' }}
  CLOUD_RUN_SERVICE: ${{ vars.CLOUD_RUN_SERVICE || 'app-service' }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT_EMAIL: ${{ vars.SERVICE_ACCOUNT_EMAIL }}
  AR_REPOSITORY: ${{ vars.AR_REPOSITORY || 'bot-images' }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve configuration
        id: cfg
        run: |
          set -euo pipefail
          REPO="${{ github.repository }}"      # e.g., owner/repo
          REF_NAME="${{ github.ref_name }}"    # branch or tag name
          TAG="${REF_NAME:-main}"

          PROJECT="${GCP_PROJECT_ID}"
          REGION="${GCP_REGION}"
          SERVICE="${CLOUD_RUN_SERVICE}"

          if [ -z "${PROJECT}" ]; then echo "::error::GCP_PROJECT_ID is not set"; exit 1; fi

          AR_HOST="${REGION}-docker.pkg.dev"
          AR_IMAGE="${AR_HOST}/${PROJECT}/${{ env.AR_REPOSITORY }}/${REPO}:${TAG}"

          echo "project=${PROJECT}" >> "$GITHUB_OUTPUT"
          echo "region=${REGION}" >> "$GITHUB_OUTPUT"
          echo "service=${SERVICE}" >> "$GITHUB_OUTPUT"
          echo "ar_host=${AR_HOST}" >> "$GITHUB_OUTPUT"
          echo "ar_image=${AR_IMAGE}" >> "$GITHUB_OUTPUT"

      # Authenticate to Google Cloud (WIF preferred)
      - name: Validate WIF inputs
        run: |
          set -euo pipefail
          if [ -z "${WORKLOAD_IDENTITY_PROVIDER:-}" ] || [ -z "${SERVICE_ACCOUNT_EMAIL:-}" ]; then
            echo "::error::WORKLOAD_IDENTITY_PROVIDER and SERVICE_ACCOUNT_EMAIL must be set as Actions variables."
            exit 1
          fi

      - name: Auth via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker "${{ steps.cfg.outputs.ar_host }}" --quiet

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image to Artifact Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.cfg.outputs.ar_image }}
          provenance: false

      - name: Deploy to Cloud Run
        env:
          IMAGE_URI: ${{ steps.cfg.outputs.ar_image }}
          ADMINS: ${{ vars.ADMINS }}
          BASE_URL: ${{ vars.BASE_URL }}
          USE_WEBHOOK: ${{ vars.USE_WEBHOOK }}
          # Optional overrides for Secret Manager secret IDs (defaults equal to env var names)
          SECRET_TELEGRAM_TOKEN: ${{ vars.SECRET_TELEGRAM_TOKEN || 'TELEGRAM_TOKEN' }}
          TELEGRAM_WEBHOOK_SECRET: ${{ vars.TELEGRAM_WEBHOOK_SECRET || 'TELEGRAM_WEBHOOK_SECRET' }}
          SECRET_WEB_USERNAME: ${{ vars.SECRET_WEB_USERNAME || 'WEB_USERNAME' }}
          SECRET_WEB_PASSWORD: ${{ vars.SECRET_WEB_PASSWORD || 'WEB_PASSWORD' }}
        run: |
          set -euo pipefail
          PROJECT="${{ steps.cfg.outputs.project }}"
          REGION="${{ steps.cfg.outputs.region }}"
          SERVICE="${{ steps.cfg.outputs.service }}"

          # Pass only non-sensitive vars via env file
          ENV_FILE="$(mktemp)"
          : > "${ENV_FILE}"
          if [ -n "${ADMINS:-}" ]; then
            echo "ADMINS: \"${ADMINS}\"" >> "${ENV_FILE}"
          fi
          if [ -n "${USE_WEBHOOK:-}" ]; then
            echo "USE_WEBHOOK: \"${USE_WEBHOOK}\"" >> "${ENV_FILE}"
          fi
          if [ -n "${BASE_URL:-}" ]; then
            echo "BASE_URL: \"${BASE_URL}\"" >> "${ENV_FILE}"
          fi

          # Always pass build metadata
          echo "GIT_COMMIT: \"${GITHUB_SHA}\"" >> "${ENV_FILE}"

          # Deploy with Secret Manager references for sensitive values
          gcloud run deploy "${SERVICE}" \
            --project "${PROJECT}" \
            --region "${REGION}" \
            --platform managed \
            --image "${IMAGE_URI}" \
            --env-vars-file="${ENV_FILE}" \
            --set-secrets "TELEGRAM_TOKEN=${SECRET_TELEGRAM_TOKEN}:latest" \
            --set-secrets "WEB_USERNAME=${SECRET_WEB_USERNAME}:latest" \
            --set-secrets "WEB_PASSWORD=${SECRET_WEB_PASSWORD}:latest"
            --set-secrets "TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}:latest"

          echo "Deployed ${SERVICE} in ${REGION} with image ${IMAGE_URI} (secrets via Secret Manager)"

      - name: Set Telegram webhook
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          BASE_URL: ${{ vars.BASE_URL }}
        run: |
          set -euo pipefail
          if [ -z "${TELEGRAM_TOKEN:-}" ] || [ -z "${BASE_URL:-}" ]; then
            echo "Skipping: TELEGRAM_TOKEN or BASE_URL not set"
            exit 0
          fi
          URL="${BASE_URL%/}/tg/webhook"
          echo "Setting webhook to ${URL}"
          RESPONSE="$(curl -sS -X POST \
            "https://api.telegram.org/bot${TELEGRAM_TOKEN}/setWebhook" \
            -d "url=${URL}")"
          echo "${RESPONSE}"
          echo "${RESPONSE}" | grep -q '"ok":true' || { echo "::error::Failed to set Telegram webhook"; exit 1; }
